name       : python-sip
version    : 4.18.1
release    : 3
source     :
    - http://freefr.dl.sourceforge.net/project/pyqt/sip/sip-4.18.1/sip-4.18.1.tar.gz : 9bce7a2dbf7f105bf68ad1bab58eebc0ce33087ec40396da756463f086ffa290
license    : GPL-3.0
component  : programming.python
summary    : python-sip is a tool that creates python2 bindings for C and C++ libraries.
description: |
    python-sip is a tool that creates python2 bindings for C and C++ libraries.
setup      : |
    python2 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install
