name       : python-sip
version    : 4.16.9
release    : 1
source     :
    - http://downloads.sourceforge.net/project/pyqt/sip/sip-4.16.9/sip-4.16.9.tar.gz : dbe173aa566e26ca0bb5bcbc1d30ef780f416267bb3b5df48149a737ea6b0555
license    : GPL-3.0
summary    : python-sip is a tool that creates python2 bindings for C and C++ libraries.
description: |
    python-sip is a tool that creates python2 bindings for C and C++ libraries.
builddeps  :
setup      : |
    python2 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install
