name       : python-sip
version    : 4.19
release    : 4
source     :
    - http://downloads.sourceforge.net/project/pyqt/sip/sip-4.19/sip-4.19.tar.gz : 014bf55f653e0d8bcc582705ef4fbd61e0859a36e959ab46d8fa060cdf0b5e27
license    : GPL-3.0
component  : programming.python
summary    : python-sip is a tool that creates python2 bindings for C and C++ libraries.
description: |
    python-sip is a tool that creates python2 bindings for C and C++ libraries.
setup      : |
    python2 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install
