name       : python-sip
version    : 4.19.13
release    : 14
source     :
    - https://netcologne.dl.sourceforge.net/project/pyqt/sip/sip-4.19.13/sip-4.19.13.tar.gz : e353a7056599bf5fbd5d3ff9842a6ab2ea3cf4e0304a0f925ec5862907c0d15e
license    : GPL-3.0-or-later
component  :
    - programming.python
    - ^python3-sip: programming.python
    - ^python3-sip-devel: programming.devel
extract    : no
summary    : python-sip is a tool that creates python and python3 bindings for C and C++ libraries.
description: |
    SIP is a tool for generating bindings for C++ classes so that they can be accessed as normal Python classes. SIP takes many of its ideas from SWIG but, because it is specifically designed for C++ and Python, is able to generate tighter bindings. SIP is so called because it is a small SWIG.
builddeps  :
    - pkgconfig(python3)
patterns   :
    - /usr/bin/sip
    - /usr/lib/python2*
    - ^python3-sip:
        - /usr/bin/sip3
        - /usr/lib/python3*
    - ^python3-sip-devel:
        - /usr/include/python3*
rundeps    :
    - ^python3-sip:
        - python-sip
setup      : |
    mkdir python2-sip
    tar xf $sources/sip-* -C python2-sip/ --strip-components=1
    cp -R $workdir/python2-sip $workdir/python3-sip
    pushd python2-sip
    python2 configure.py --sip-module PyQt5.sip CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
    popd
    pushd python3-sip
    python3 configure.py --sip-module PyQt5.sip CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
    sed -i 's/TARGET = sip/TARGET = sip3/' sipgen/Makefile
    popd
build      : |
    pushd python2-sip
    %make
    popd
    pushd python3-sip
    %make
    popd
install    : |
    pushd python2-sip
    %make_install
    popd
    pushd python3-sip
    %make_install
    popd
