name       : python-sip
version    : 4.19.7
release    : 7
source     :
    - https://netcologne.dl.sourceforge.net/project/pyqt/sip/sip-4.19.7/sip-4.19.7.tar.gz : 25b50d29dd4b72965e7980c41e3320e460eff481a177beeddebf8c3be84b8cde
license    : GPL-3.0
component  : programming.python
summary    : python-sip is a tool that creates python bindings for C and C++ libraries.
description: |
    SIP is a tool for generating bindings for C++ classes so that they can be
    accessed as normal Python classes. SIP takes many of its ideas from SWIG but,
    because it is specifically designed for C++ and Python, is able to generate
    tighter bindings. SIP is so called because it is a small SWIG.
setup      : |
    python2 configure.py CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install
