name       : python-sip
version    : 6.4.0
release    : 24
source     :
    - https://files.pythonhosted.org/packages/source/s/sip/sip-6.4.0.tar.gz : 42ec368520b8da4a0987218510b1b520b4981e4405086c1be384733affc2bcb0
homepage   : https://www.riverbankcomputing.com/software/sip
license    : GPL-3.0-or-later
component  : programming.python
summary    : python-sip is a tool that creates python 3 bindings for C and C++ libraries
description: |
    SIP is a tool for generating bindings for C++ classes so that they can be accessed as normal Python classes. SIP takes many of its ideas from SWIG but, because it is specifically designed for C++ and Python, is able to generate tighter bindings. SIP is so called because it is a small SWIG.
replaces   :
    - python3-sip
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-packaging
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
