name       : python-sip
version    : 4.19.19
release    : 17
source     :
    - https://www.riverbankcomputing.com/static/Downloads/sip/4.19.19/sip-4.19.19.tar.gz : 5436b61a78f48c7e8078e93a6b59453ad33780f80c644e5f3af39f94be1ede44
license    : GPL-3.0-or-later
component  :
    - programming.python
    - ^python3-sip : programming.python
    - ^python3-sip-devel : programming.devel
summary    :
    - python-sip is a tool that creates python 2 bindings for C and C++ libraries
    - ^python3-sip : python3-sip is a tool that creates python 3 bindings for C and C++ libraries
    - ^python3-sip-devel : Development files for python3-sip
description: |
    SIP is a tool for generating bindings for C++ classes so that they can be accessed as normal Python classes. SIP takes many of its ideas from SWIG but, because it is specifically designed for C++ and Python, is able to generate tighter bindings. SIP is so called because it is a small SWIG.
builddeps  :
    - pkgconfig(python3)
patterns   :
    - /usr/bin/sip
    - /usr/lib/python2*
    - ^python3-sip :
        - /usr/bin/sip3
        - /usr/lib/python3*
    - ^python3-sip-devel :
        - /usr/include/python3*
rundeps    :
    - ^python3-sip :
        - python-sip
    - ^python3-sip-devel :
        - python3-sip
setup      : |
    instdir=$(basename $PWD)
    cd ..
    echo py2build py2build-pyqt5 py3build py3build-pyqt5 | xargs -n 1 cp -a $instdir
    rm -fr $instdir

    pushd py2build
        python2 configure.py CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
    popd
    pushd py3build
        python3 configure.py CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
        sed -i 's/TARGET = sip/TARGET = sip3/' sipgen/Makefile
    popd
    pushd py2build-pyqt5
        python2 configure.py --sip-module PyQt5.sip --no-tools --no-dist-info \
        CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
    popd
    pushd py3build-pyqt5
        python3 configure.py --sip-module PyQt5.sip --no-tools --no-dist-info \
        CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
    popd
build      : |
    %make -C py2build
    %make -C py3build
    %make -C py2build-pyqt5
    %make -C py3build-pyqt5
install    : |
    %make_install -C py2build-pyqt5
    %make_install -C py3build-pyqt5
    %make_install -C py2build
    %make_install -C py3build
