name       : python-sip
version    : 4.19.2
release    : 5
source     :
    - https://downloads.sourceforge.net/project/pyqt/sip/sip-4.19.2/sip-4.19.2.tar.gz : 432b4aad25254e6997913e33b1ca3cf5fd21d5729a50a3ce2edccbea82c80533
license    : GPL-3.0
component  : programming.python
summary    : python-sip is a tool that creates python2 bindings for C and C++ libraries.
description: |
    python-sip is a tool that creates python2 bindings for C and C++ libraries.
setup      : |
    python2 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install
